version: '3'
services:
  tokoencount:
    build: ./
    entrypoint: dockerize -timeout 60s -wait tcp://mysql:3306
    command: ./TOKO-ENCOUNT
    ports:
      - 3050:80
    depends_on:
      - mysql

  mysql:
    image: mariadb:10.7.3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chatdb
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - "./sql/init.sql:/docker-entrypoint-initdb.d/init.sql"
    expose:
      - "3306"
