openapi: 3.0.3

info:
  title: TOKO-ENCOUNT
  version: 0.0.1
  description:  TOKO-ENCOUNT API

servers:
  - url: localhost:3050

paths:
  '/api/login':
    post:
      summary: ログイン
      operationId: postLogin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserSimple"
      responses:
        '200':
          description: ログインに成功しました
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserWithoutPass"

  '/api/logout':
    post:
      summary: ログアウト
      operationId: postLogout
      responses:
        '200':
          description: ログアウトに成功しました

  '/api/user':
    post:
      tags:
        - user
      summary: アカウント作成
      operationId: postUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        '200':
          description: アカウント作成に成功しました
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserWithoutPass"
    get:
      tags:
        - user
      summary: ユーザー検索
      operationId: getUsers
      parameters:
        - name: limit
          in: query
          description: 取得するユーザーの最大数
          schema:
            type: integer
            default: 20
        - name: offset
          in: query
          description: 何件目のユーザーから取得するか
          schema:
            type: integer
            default: 0
        - name: name
          in: query
          description: ユーザーの名前で検索
          schema:
            type: string
        - name: gender
          in: query
          description: ユーザーの性別で検索
          schema:
            type: string
        - name: prefect
          in: query
          description: ユーザーの都道府県で検索
          schema:
            type: string
      responses:
        '200':
          description: 取得できたユーザー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserList"

  '/api/user/me':
    get:
      tags:
        - user
      summary: 自分のユーザー情報を取得
      operationId: getUserMe
      responses:
        '200':
          description: アカウント情報
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserWithoutPass"
    patch:
      tags:
        - user
      summary: プロフィール編集
      operationId: patchUserMe
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        '200':
          description: プロフィール編集に成功しました
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserWithoutPass"

  '/api/chat':
    get:
      tags:
        - chat
      summary: 参加中のチャット一覧を表示
      operationId: getChat
      parameters:
        - name: limit
          in: query
          description: 取得するチャットの最大数
          schema:
            type: integer
            default: 20
        - name: offset
          in: query
          description: 何件目のチャットから取得するか
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: チャット情報
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ChatList"

  /api/chat/{cid}:
    get:
      tags:
        - chat
      summary: cidのチャット内のメッセージを取得
      operationId: getChatMessages
      parameters:
        - name: cid
          in: path
          required: true
          description: チャットID(全体チャットは0)
          schema:
            type: string
            format: uuid
        - name: limit
          in: query
          description: 取得するメッセージの最大数
          schema:
            type: integer
            default: 20
        - name: offset
          in: query
          description: 何件目のメッセージから取得するか
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: メッセージ情報
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageList"

components:
  schemas:
    User:
      type: object
      properties:
        userName:
          type: string
          example: testUserName
        password:
          type: string
          example: "********"
        prefect:
          type: string
          example: 東京都
        gender:
          type: string
          example: male
      required:
        - userName
        - password
        - prefect
        - gender

    UserSimple:
      type: object
      properties:
        userName:
          type: string
          example: testUserName
        password:
          type: string
          example: "********"
      required:
        - userName
        - password

    UserWithoutPass:
      type: object
      properties:
        userId:
          type: string
          format: uuid
        userName:
          type: string
          example: testUserName
        prefect:
          type: string
          example: 東京都
        gender:
          type: string
          example: male
      required:
        - userId
        - userName
        - prefect
        - gender

    UserList:
      type: object
      properties:
        hasNext:
          type: boolean
        users:
          type: array
          items:
            $ref: "#/components/schemas/UserWithoutPass"
      required:
        - hasNext
        - users

    Message:
      type: object
      properties:
        chatId:
          type: string
          format: uuid
        post:
          type: string
          example: hello
        postUserId:
          type: string
          format: uuid
        userName:
          type: string
          example: testUserName
        createdAt:
          type: string
          format: date-time
      required:
        - chatId
        - post
        - postUserId
        - userName
        - createdAt

    MessageList:
      type: object
      properties:
        hasNext:
          type: boolean
        messages:
          type: array
          items:
            $ref: "#/components/schemas/Message"
      required:
        - hasNext
        - messages

    ChatData:
      type: object
      properties:
        name:
          type: string
        latestMessage:
          $ref: "#/components/schemas/Message"
        newMessageCount:
          type: integer
      required:
        - name
        - latestMessage
        - newMessageCount

    ChatList:
      type: object
      properties:
        hasNext:
          type: boolean
        chats:
          type: array
          items:
            $ref: "#/components/schemas/ChatData"
      required:
        - hasNext
        - chats
